### ISSUE TITLE
Feature Request: Compare two files in vault?

### ISSUE THREAD

**Issue by ReaderGuy42** [kometenstaub/obsidian-version-history-diff#15]
Would it be possible to add a function to compare two files?

E.g. you send someone a note to proof read, get it back, and want to see what they did? I think your plugin would be ideal for this?

If the plugin already does this, apologies, could you tell me how then?

Thanks!

**Comment by kometenstaub** [comment]
This may be possible, but not something I want to implement.

Currently, the plugin works by getting the active file path and then accessing the versions for it.
Someone would need to build a different UI for choosing two files and displaying their difference without the versions on both sides, which should be its own plugin because this plugin is not built for that.

**Comment by dagomar** [comment]
That's a real shame. My use-case is to keep notes in-sync with template changes, which I accomplish now with an external tool (Meld).

**Comment by kometenstaub** [comment]
There’s this plugin: <obsidian://show-plugin?id=file-diff>
